marble: parts: remove prox check
Superior doesn't have this commit: https://github.com/LineageOS/android_frameworks_base/commit/1478727fd9c10385c86eb7ff0cbea796292bb889
so this will fail. Remove it for now

device/xiaomi/marble/parts/src/org/lineageos/settings/doze/PickupSensor.java:76: error: cannot find symbol
                mPowerManager.wakeUpWithProximityCheck(SystemClock.uptimeMillis(),
                             ^
  symbol:   method wakeUpWithProximityCheck(long,int,String)
  location: variable mPowerManager of type PowerManager

Change-Id: 5874f12862772804b68f7a37beaf714aa69b912b
Signed-off-by: frozenking <frozenking1240196@gmail.com>